# Generated by Django 5.2.8 on 2025-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
