# Generated by Django 5.2.8 on 2025-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Почта"
            ),
        ),
    ]
