# Generated by Django 5.2.8 on 2025-11-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects",
                to="main.student",
                verbose_name="Студент",
            ),
        ),
    ]
